FROM python:3.10.14

WORKDIR /home/work

COPY requirements.txt ./requirements.txt
RUN python -m pip install -U pip
RUN pip install --no-cache-dir -r requirements.txt 

COPY src src
COPY app.py app.py

EXPOSE 8001
CMD ["uvicorn" ,"app:app" , "--host", "0.0.0.0", "--reload", "--port", "8001"]


